import type { Model } from "./types.js";

const ZERO_COST = {
  input: 0,
  output: 0,
  cacheRead: 0,
  cacheWrite: 0,
};

export const MODELS = {
  ollama: {
    "llama3.1": {
      id: "llama3.1",
      name: "Llama 3.1",
      api: "ollama-chat",
      provider: "ollama",
      baseUrl: "https://api.ollama.com/api",
      reasoning: false,
      input: ["text"],
      cost: ZERO_COST,
      contextWindow: 128000,
      maxTokens: 8192,
    } satisfies Model<"ollama-chat">,
    "qwen2.5": {
      id: "qwen2.5",
      name: "Qwen 2.5",
      api: "ollama-chat",
      provider: "ollama",
      baseUrl: "https://api.ollama.com/api",
      reasoning: false,
      input: ["text"],
      cost: ZERO_COST,
      contextWindow: 128000,
      maxTokens: 8192,
    } satisfies Model<"ollama-chat">,
  },
  openrouter: {
    "openrouter/auto": {
      id: "openrouter/auto",
      name: "OpenRouter Auto",
      api: "openai-completions",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      reasoning: true,
      input: ["text", "image"],
      cost: ZERO_COST,
      contextWindow: 128000,
      maxTokens: 16384,
      compat: {
        supportsStore: false,
        supportsDeveloperRole: false,
        thinkingFormat: "openrouter",
        maxTokensField: "max_tokens",
      },
    } satisfies Model<"openai-completions">,
    "anthropic/claude-sonnet-4.5": {
      id: "anthropic/claude-sonnet-4.5",
      name: "Claude Sonnet 4.5",
      api: "openai-completions",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      reasoning: true,
      input: ["text", "image"],
      cost: ZERO_COST,
      contextWindow: 200000,
      maxTokens: 16384,
      compat: {
        supportsStore: false,
        supportsDeveloperRole: false,
        thinkingFormat: "openrouter",
        maxTokensField: "max_tokens",
      },
    } satisfies Model<"openai-completions">,
    "openai/gpt-5.1": {
      id: "openai/gpt-5.1",
      name: "GPT-5.1",
      api: "openai-completions",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      reasoning: true,
      input: ["text", "image"],
      cost: ZERO_COST,
      contextWindow: 400000,
      maxTokens: 16384,
      compat: {
        supportsStore: false,
        supportsDeveloperRole: false,
        thinkingFormat: "openrouter",
        maxTokensField: "max_tokens",
      },
    } satisfies Model<"openai-completions">,
  },
} as const;
